FROM ubuntu:18.04

RUN apt-get update && apt-get upgrade --assume-yes && \
    apt-get install --assume-yes tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get install --assume-yes \
    libcurl4-openssl-dev \
    git-all \
    icnsutils \
    graphicsmagick \
    build-essential \
    wget

# START - install Node
# TODO: Move this to pre-built version of Node once 18.04 is released
RUN apt-get install --assume-yes python
RUN wget -q https://nodejs.org/dist/v8.11.1/node-v8.11.1.tar.gz && \
    tar -xvf node-v8.11.1.tar.gz && \
    cd node-v8.11.1 && \
    ./configure && \
    make -j4 && \
    make install
# END - install Node

# Install required (optional) dependency
ADD packages/insomnia-app /app
WORKDIR /app

RUN npm install 7zip-bin-linux && npm install

VOLUME /app/dist
CMD npm run package
